### ISSUE TITLE
Refactor round and game no

### ISSUE THREAD

**Issue by ssardina** [ssardina/pynbl#8]
We should only keep round number. 

Game numbers per team should be calculated from the games recorded, which anyway include the date

**Comment by ssardina** [comment]
@jgalowe , I have done a major restructuring/refactor after we discussed. Now I think you get the idea of having "normalized'  tables that don't repeat data or have noisy data built in.

So, in the new version:

- no game numbers for any team, just round number
- round number ONLY appears in game table, not in the stats tables we will be building (at this point we only have stints lineup stats). However, as we discussed one can always recover the round of a game via its `game_id`
- have also added a table `stints_df` which stores the stint data of each game and each team. Basically the lineups, no of minutes, periods, etc.. This is already also in the stint stats, but we may need these table later on so better produce it.

Makes sense?

**Comment by jgalowe** [comment]
Great thank you. 

I don't understand though - Why do we need the second stints_df table if we already have it? Will it be removed from the main table?

**Comment by ssardina** [comment]
Your question suggests you do understand it. :-) 

You are right it is technically not needed, as the stint stats has all the info of each stint. I use it before extracting the stats, so I have saved it just in case I need it later. But yes it may not be needed to keep it around, you are right! :clap: :clap: :clap:
